name: facebook_sign_in
description: Sign in with Facebook for Flutter apps
version: 0.0.1
author: Boris Onchev
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.boriso.facebooksignin.facebook_sign_in
    pluginClass: FacebookSignInPlugin
